### ISSUE TITLE
RTC attributes in raw data

### ISSUE THREAD

**Issue by srikanth288** [dixudx/rtcclient#132]
Hi, I am trying to invoke RTC api, and i am able to access all the custom attriubytes, however there are some custom ones which i can see in the raw data but not able to access it . Below is one such example

('rtc_cm:XXXXX.incident.attribute.intialanalysisOwner'
 OrderedDict([('@rdf:resource'
 'https://jazz.fssa.in.gov:9443/jts/users/XXXX')]))
 ('rtc_cm:XXXXX.incident.attribute.incidentresolvedwithinitialAnalysis'
 OrderedDict([('@rdf:resource'
 'https://jazz.XXXXX:9443/ccm/oslc/enumerations/_fBSG8KLVEeKfqNMyp7eVKg/XXXXX.incident.enumeration.incidentinitialAnalysis/XXXXX.incident.enumeration.incidentinitialAnalysis.literal.l7')]))
 ('rtc_cm:XXXXX.incident.attribute.incidentResolutionowner'
 OrderedDict([('@rdf:resource'
 'https://jazz.XXXXX:9443/jts/users/XXXXX')]))

    returned_properties = "oslc_cm:severity,rtc_cm:teamArea,rtc_cm:ownedBy,rtc_cm:XXX.incident.attribute.incidentResolutionowner"
    for item in list:
        wk = myclient.getWorkitem(item,returned_properties)
        print(wk['incidentResolutionowner'])

i get error saying there is not Incident resolution owner attribute.

**Comment by dixudx** [comment]
@srikanth288 For such long `rtc_cm:XXX.incident.attribute.incidentResolutionowner` is ignored. This is by design, since the last field name, such as `incidentResolutionowner`, will get conflict with other `rtc_cm:abc.def.ghi.incidentResolutionowner`.

You can refer to [this guide about returned attributes](https://rtcclient.readthedocs.io/en/latest/quickstart.html#about-returned-properties) that you can use with dot method.

**Comment by srikanth288** [comment]
Thanks for the response, i would need that that for my functionality, i used Plain old Java lib for RTC part thanks . Closing the issue
