### ISSUE TITLE
How do I query RTC work items with a time range?

### ISSUE THREAD

**Issue by ravir4** [dixudx/rtcclient#71]
I am trying to use the RTC python API ( https://pypi.python.org/pypi/rtcclient/0.2.0 ) to query workitems that have been created within a certain time frame (i.e between July 1 and Jan 1). 

I am using the queryWorkitems call  and the  property dc:created to do that but not having much luck with the format / syntax for a range.

This is what I am trying to do and it fails with a - TypeError: 'NoneType' object is not iterable

query_string = ('dc:created>="07-01-2015T01:00:00Z" and dc:created<"01-01-2016T01:00:00Z"')

I have tried reversing the > and < and didn't have much luck either

turning on debug shows - INFO query:Query: Start to query workitems with query string: dc:created>="07-01-2015T01:00:00Z" and dc:created<"01-01-2016T01:00:00Z"

I am able to get data for 

query_string = ('dc:created>="07-01-2015T01:00:00Z"')

and also this works

query_string = ('dc:created>="07-01-2015T01:00:00Z" and dc:type="defect"')

Any help would be greatly appreciated.

**Comment by dixudx** [comment]
1. Now the latest version of rtcclient is [0.5.0](https://pypi.python.org/pypi/rtcclient/0.5.0). I think you can update to 0.5.0 and have another try;

   ```
   pip install -U rtcclient
   ```

2. A little confused on the query_string type, which you got was actually a tuple, not a string;

3. Could you provide some more detailed logs, so that I can figure out some clues;

4. For the query syntax, you can refer to [query_syntax](http://rtcclient.readthedocs.org/en/latest/advanced_usage.html#query-syntax);

5. You can try the new feature, querying work items by saved query ( or url ). See [this page](http://rtcclient.readthedocs.org/en/latest/quickstart.html#query-workitems-by-saved-query) for more information.

**Comment by dixudx** [comment]
Another question here

have you ever queried these work items with your above filters on your jazz web page ? any results ?

**Comment by ravir4** [comment]
Thank you for your response. Yes i did a query and I didn't have any hits for the time range, hence the decision to post.

I had updated to your latest version.

Finally figured out the solution - it was the date format

I was using the format in your example query string but if I switch it to YYYY-MM-DD it works fine. So this one works (atleast it moved past the error and still running)

query_string = ('dc:created>="2015-07-01T01:00:00Z" and dc:created<"2016-01-01T01:00:00Z"')

What I observed is : This one works --> dc:created>="07-01-2015T01:00:00Z

but this one doesn't ---> dc:created<"07-01-2015T01:00:00Z

(greater than works in that format but less than doesn't)

Thanks again

**Comment by dixudx** [comment]
Good job. Thanks for your investigation and solution.

The time format (`YYYY-MM-DD`, `MM-DD-YYYY`, or etc) may differ per system, which may relates to the settings(preferences), versions of RTC server and etc. And the format can be acquired from the detailed information by getting a specific workitem.
